# Generated by Django 3.0.8 on 2020-07-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(blank=True, max_length=60, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='media/profile_photos')),
                ('location', models.CharField(blank=True, max_length=80, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('mail', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=100)),
                ('web_site', models.URLField(blank=True, max_length=100)),
            ],
        ),
    ]
