# Generated by Django 3.0.8 on 2020-07-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalmodel',
            name='description',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalmodel',
            name='position',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
