# Generated by Django 3.0.8 on 2020-07-30 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_generalmodel_file_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_desc', models.TextField()),
                ('experience', models.IntegerField()),
                ('happy_client', models.IntegerField()),
                ('follower_facebook', models.IntegerField()),
                ('finished_project', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JobSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_name', models.CharField(blank=True, max_length=120, null=True)),
                ('skills_interest', models.FloatField(default=0)),
                ('skills_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.SkillsModel')),
            ],
        ),
    ]
