# Generated by Django 3.0.8 on 2020-07-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0007_experiencemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_name', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(default='Present')),
                ('job_title', models.CharField(max_length=120)),
                ('desrp', models.TextField()),
                ('edu_logo', models.ImageField(blank=True, null=True, upload_to='media/edo_logo')),
            ],
        ),
    ]
