# Generated by Django 3.0.8 on 2020-07-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_auto_20200730_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalmodel',
            name='file_cv',
            field=models.FileField(default=True, upload_to=''),
            preserve_default=False,
        ),
    ]
