# Generated by Django 3.0.8 on 2020-07-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_jobskills_skillsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobskills',
            name='js_interest',
            field=models.CharField(default=True, max_length=15),
            preserve_default=False,
        ),
    ]
