# Generated by Django 3.0.8 on 2020-07-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0008_educationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=120)),
                ('project_image', models.ImageField(blank=True, null=True, upload_to='media/project_images')),
                ('project_link', models.URLField()),
            ],
        ),
    ]
